name: pa_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  go_router: ^13.2.0
  skeletonizer: ^2.1.1
  flutter_native_splash: ^2.4.7
  cached_network_image: ^3.3.1
  lottie: ^3.1.0


# Dev Dependencies Area
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/fonts/jura/
     - assets/lottie/
     - assets/rive/


  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/jura/Jura-Light.ttf
          weight: 300
        - asset: assets/fonts/jura/Jura-Regular.ttf
          weight: 400
        - asset: assets/fonts/jura/Jura-Medium.ttf
          weight: 500
        - asset: assets/fonts/jura/Jura-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jura/Jura-Bold.ttf
          weight: 700


# Native Splash Screen Config
flutter_native_splash:
  color: "#181619"
  image: assets/images/logo/app_logo.jpg
  android: true
  ios: true
  android_12:
    image: assets/images/logo/app_logo.jpg
    icon_background_color: "#181619"